### ISSUE TITLE
missing html prefix in page-list

### ISSUE THREAD

**Issue by peppobon** [transpect/epubtools#3]
Hi,
in the generated nav list the li/@href is missing the html-prefix resulting in invalid epubs.

Patch:
in epubtools/modules/html-splitter/xsl/html-splitter.xsl, line 1318 use the following corrected template

`
<xsl:template name="page-list-nav-inner">
    <nav epub:type="page-list" id="page-list-navigation" hidden="hidden">
      <ol>
        <xsl:for-each select="$pgl/html:page[normalize-space(@name)]">
          <li>
            
            <a href="{concat($html-prefix, @href)}" srcpath="pgl_{generate-id()}">
              <xsl:value-of select="@name"/>
            </a>
          </li>
        </xsl:for-each>
      </ol>
    </nav>
  </xsl:template>
`

**Comment by gimsieke** [comment]
If you say so, Peppo. 

Maybe we didn’t notice before since we don’t seem to use `$html-subdir-name`.

Thanks, I blindly applied the patch (in slightly other words) and started our tests.

**Comment by mkraetke** [comment]
Hi @peppobon,

unfortunately this case was not covered by our tests. For one of our customers, many invalid EPUBs were generated because of this commit. Can you provide me a sample of your input file, so I can figure out how to solve this issue.

Thank you,
Martin

**Comment by gimsieke** [comment]
Shouldn’t the nav list HTML file be written to the same `$html-subdir` as the other pages? Then this relative path shouldn’t be necessary.

**Comment by peppobon** [comment]
I am sorry, but I cannot find my test case that originated this issue.
You can close this issue reverting back.
Sorry for the inconvenience this have caused.

**Comment by mkraetke** [comment]
Thank you and don't hesitate to report, if this issue might occur again.
