### ISSUE TITLE
toc wrong order in opf spine

### ISSUE THREAD

**Issue by peppobon** [transpect/epubtools#4]
There is a typo preventing having the toc after the cover in opf spine.

Change line 1262 in epubtools/modules/html-splitter/xsl/html-splitter.xsl line
from 
`<meta name="sequence" content="($epub-config/types/@nav-spine-pos, 1.5)[1]"/>`
to
`<meta name="sequence" content="{($epub-config/types/@nav-spine-pos, 1.5)[1]}"/>`
i.e. missing {} in @content.

**Comment by mkraetke** [comment]
Hi @peppobon,

thank you much for the report. I've fixed this issue as you recommended.

Kind regards,
Martin
