### ISSUE TITLE
css-handling="unchanged" behaviour

### ISSUE THREAD

**Issue by peppobon** [transpect/epubtools#5]
Currently the css-handling parameter trigger the css handling even when its value is "unchanged" and therefore the epub generation fails in case of css parsing errors. 

Would it be possible to completely skip the css parsing when css-handling="unchanged" and copy over in the generated epub whatever css files are in the sources (ideally inserting also the relevant manifest entries) ?

This would help also with valid but complex css as the css parsing is quite slow.

**Comment by gimsieke** [comment]
Please update epubtools and see whether CSS parsing will now be skipped. I just did a very basic test and I think it works as expected.

**Comment by peppobon** [comment]
Many thanks Gerrit: it works
